version: '3.9'

x-server: &server
  container_name: server
  restart: always
  env_file: ./packages/commonwealth/.env
  volumes:
    - .:/commonwealth
  build:
    context: ./
    dockerfile: ./packages/commonwealth/Dockerfile
    args:
      - PORT=8080
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis:6379
      - DATABASE_URL=postgresql://commonwealth:edgeware@postgres/commonwealth
  ports:
    - '8080:8080'
  expose:
    - '8080'

services:
  # runs on "docker compose up". Fully dockerized commonwealth.
  server:
    <<: *server
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: db
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=commonwealth
      - POSTGRES_DB=commonwealth
      - POSTGRES_PASSWORD=edgeware
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/docker-volumes/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/docker-volumes/redis-data:/var/lib/redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ${PWD}/docker-volumes/rmq/data:/var/lib/rabbitmq
      - ${PWD}/docker-volumes/rmq/log:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10

  # base server + host postgres
  server-external-db:
    <<: *server
    build:
      args:  # Uses host db by default, change this URI for db outside of host
        - DATABASE_URL=postgresql://commonwealth:edgeware@host.docker.internal/commonwealth
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - separate