version: '3.9'
services: 
  builder: 
    image: builder
    build: .
  db:
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: "${DOCKER_PG_PW}" 
      POSTGRES_USER: "${DOCKER_PG_USER}" 
    ports:
      - "5432:5432"
    build: 
      context: .
  rabbitmq: 
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  common-common:
    build: packages/common-common
  chain-events: 
    build: packages/chain-events
  commonwealth: 
    build:
      context: .
      dockerfile: packages/commonwealth/Dockerfile
    hostname: commonwealth-server
    depends_on:
      - db
      - rabbitmq
    ports: 
      - "8080:8080"
    volumes:
      - ./:/monorepo
volumes:
  db:
    driver: local
networks: 
  rabbitmq_go_net:
    driver: bridge

    


