# This compose file is used to store base definitions that other compose files can extend
version: '3.9'
services:
  base_server:
    restart: always
    env_file: ./packages/commonwealth/.env
    build:
      context: ./
      dockerfile: ./packages/commonwealth/Dockerfile
      args:
        - PORT=8080
        - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
        - REDIS_URL=redis:6379
        - DATABASE_URL=postgresql://commonwealth:edgeware@postgres/commonwealth
    ports:
      - '8080:8080'
    expose:
      - '8080'
