version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring_network
    restart: always

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_storage:/var/lib/influxdb
    networks:
      - monitoring_network
    restart: always
    environment:
      - INFLUXDB_DB=artillerydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user

volumes:
  grafana_storage:
  influxdb_storage:

networks:
  monitoring_network:
