version: "2.2"
services:
  jobmanager:
    image: flink:1.16.2-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - notification_service_network

  taskmanager:
    image: flink:1.16.2-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - notification_service_network

  notifications_service:
    container_name: notifications_service
    build:
      dockerfile: dev.Dockerfile
      context: ../packages/notifications-service
    tty: true
    environment:
      - FLINK_MASTER=jobmanager:8081
    volumes:
      - ../packages/notifications-service:/root
    networks:
      - notification_service_network

networks:
  notification_service_network:
    name: notification_service_network
