version: "2.2"
services:
  jobmanager:
    image: flink:1.16.2-scala_2.12
    ports:
      - "127.0.0.1:8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.16.2-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
  beam_job_service:
    image: apache/beam_flink1.16_job_server:latest
    depends_on:
      - jobmanager
      - taskmanager
    network_mode: host
    command: --flink-master=localhost:8081

