version: "3.0"
services:
  local-db:
    container_name: local-db
    image: library/postgres:latest
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=commonwealth
      - POSTGRES_PASSWORD=edgeware
      - POSTGRES_DB=commonwealth
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  local-rabbitmq:
    container_name: local-rabbitmq
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./mq-init.sh:/mq-init.sh
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    entrypoint: ["sh", "-c", "sh /mq-init.sh"]