name: CI
on: [push]

jobs:
  commonwealth:
    name: Commonwealth Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14 ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: commonwealth
          POSTGRES_DB: commonwealth
          POSTGRES_PASSWORD: edgeware
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ matrix.node }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --ignore-engines

      - name: Run e2e tests
        run: DATABASE_URL="postgresql:/""/commonwealth:edgeware@postgres/commonwealth" yarn --cwd packages/commonwealth start & (yarn --cwd packages/commonwealth wait-server && yarn --cwd packages/commonwealth test-e2e)
      - name: Run Token Balance Cache Unit Tests
        run: yarn --cwd packages/token-balance-cache test

      - name: Run Chain Events Unit Tests
        run: yarn --cwd packages/chain-events unit-test

#      - name: Cache browsers
#        id: playwright-cache
#        uses: actions/cache@v3
#        with:
#          path: '~/.cache/ms-playwright'
#          key: ${{ matrix.node }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#
#      - name: Install playwright browser drivers
#        if: steps.playwright-cache.outputs.cache-hit != 'true'
#        run: npx playwright install --with-deps

#      - name: Run e2e tests
#        run: DATABASE_URL=postgresql://commonwealth:edgeware@postgres/commonwealth yarn --cwd packages/commonwealth start & (yarn --cwd packages/commonwealth wait-server && yarn --cwd packages/commonwealth test-e2e)

      - name: Typecheck
        run: yarn --cwd packages/commonwealth check-types

      - name: Run unit tests
        run: yarn --cwd packages/commonwealth unit-test

      - name: Run API tests
        run: yarn --cwd packages/commonwealth test-api
        env:
          NO_CLIENT: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
