name: Convert PRs to Drafts without Linked Issue

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  checkLinkedIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return -1;
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"