name: Convert PRs to Drafts without Linked Issue

on:
  pull_request:
    types:
      - opened

jobs:
  checkLinkedIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has a linked issue
        id: check_issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prDescription = context.payload.pull_request.body;
            const issueMatcher = /[cC]loses:\s*#(\d+)/;
            
            let prNumber = -1;
            if (!issueMatcher.test(prDescription)) {
              prNumber = context.payload.number
            }
            
            return prNumber.toString();
          result-encoding: string

      - name: Draft Existing PR
        if: ${{ steps.check_issue.outputs.prNumber != '-1' }}
        uses: softprops/action-update-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ steps.check_issue.inputs.pr_number }}
          draft: true